require("user.settings")
require("user.plugins")
require("user.alphadash")
require("user.neotree")
require("user.lsp")
require("user.keymaps")
require("user.kanagawa")
require("user.treesitter")
require("user.toggleterm")
-- require("user.noice")
-- require("user.nvim-tree")
-- require("user.oil")
require("user.telescope")
require("user.devicons")
require("user.neoformat")
-- require("user.glance")
require("user.lualine")
