require("user.settings")
require("user.plugins")
require("user.neoformat")
require("user.lsp")
require("user.keymaps")
require("user.kanagawa")
require("user.treesitter")
require("user.toggleterm")
require("user.noice")
-- require("user.nvim-tree")
-- require("user.oil")
require("user.telescope")
require("user.neotree")
-- require("user.telescope-browser")
require("user.lualine")
